### PR TITLE
Adding CI

### PR DESCRIPTION
**Pull request by sudarsan-surendralal**
Adding content necessary for continuous integration

### CODE REVIEW

**Comment by jan-janssen** [comment]
@niklassiemer  and I spend quite some time to develop https://github.com/pyiron/pyiron_module_template is it possible to use this template for this repository? It should really simplify the development of new pyiron modules and helps us to keep the CI environment consistent.

**Comment by jan-janssen** [comment]
https://github.com/pyiron/pyiron_module_template/issues/1

**Comment by sudarsan-surendralal** [comment]
> 
> 
> @niklassiemer and I spend quite some time to develop https://github.com/pyiron/pyiron_module_template is it possible to use this template for this repository? It should really simplify the development of new pyiron modules and helps us to keep the CI environment consistent.

Okay let me give it a shot!

**Comment by liamhuber** [comment]
> @niklassiemer and I spend quite some time to develop https://github.com/pyiron/pyiron_module_template is it possible to use this template for this repository? It should really simplify the development of new pyiron modules and helps us to keep the CI environment consistent.

This is really stellar! I was aware of the project template, but for me this is actually much more useful but had somehow flown under my radar/managed to be forgotten.

@niklassiemer, could you give a short workshop tutorial on how and when to use this as part of a pyiron or ADIS meeting in the next few weeks? @jan-janssen a short tutorial on how/when to use the project template also probably wouldn't hurt, but I think more people are aware of it already so it's probably lower priority.

**Comment by sudarsan-surendralal** [comment]
I've recreated this repository using the template [here](https://github.com/pyiron/pyiron_electrochemistry) and it works well.

**Pull request closed without merging**
